FROM adoptopenjdk/openjdk8:alpine-jre

#ARG JAR_FILE=target/hello-docker-0.0.1-SNAPSHOT.jar

WORKDIR /opt/app

COPY /docker-spring/target/hello-docker-0.0.1-SNAPSHOT.jar /opt/app/app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]